# Generated by Django 5.1.6 on 2025-03-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dorixona",
            name="image",
            field=models.ImageField(
                blank=True,
                default="defaults/default.jpeg ",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
